name: CV3.7
channels:
  - defaults
dependencies:
  - pip=20.2.2=py37_0
  - python=3.7.9
  - pip:
    - jupyter==1.0.0
    - matplotlib==3.3.2
    - numpy==1.18.0
    - scikit-image==0.17.2
    - scikit-learn==0.23.2
    - tensorflow==2.3.1
